version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resumeChallenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mjne9b1goafd"
s3_prefix = "resumeChallenge"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
